#
# Kbuild for the EXOFS module
#
# Copyright (C) 2008 Panasas Inc.  All rights reserved.
#
# Authors:
#   Boaz Harrosh <bharrosh@panasas.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
#
# Kbuild - Gets included from the Kernels Makefile and build system
#

# ore module library
libore-y := ore.o ore_raid.o
obj-$(CONFIG_ORE) += libore.o

exofs-y := inode.o file.o symlink.o namei.o dir.o super.o sys.o

# below is for export_ioctl (Ganesha PNFS)
ccflags-y += -D__linux__=1 -DKERNEL=1
exofs-y += pnfs_layout_logic.o export_ioctl.o pnfs_osd_xdr_srv.o

obj-$(CONFIG_EXOFS_FS) += exofs.o
